version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start
    environment:
      - MONGO_URI=mongodb+srv://taida22it_db_user:AUueJn4k0EM2sskh@anhtai.ojuuoai.mongodb.net/?retryWrites=true&w=majority&appName=anhtai
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
