version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME}/mern-backend:latest
    restart: unless-stopped
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - CHATBOT_API_KEY=${CHATBOT_API_KEY}
    ports:
      - "4000:4000"
    networks:
      - app-network

  client:
    image: ${DOCKER_USERNAME}/mern-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
