name: Simple Test

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World! GitHub Actions is working!"
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Show repository contents
        run: |
          echo "=== Repository Contents ==="
          ls -la
          echo "=== Server Directory ==="
          ls -la server/ || echo "Server directory not found"
          echo "=== Client Directory ==="
          ls -la client/ || echo "Client directory not found"